[fishing]
ultra = """🌟【99积分】🌟
金光闪闪！幸运之神啾咪了你一口！
ฅ( ̳• ◡ • ̳)ฅ捕获稀有星辰碎片★
恭喜解锁传说级摸鱼成就！快去买彩票啦～"""
big = """🌸【50积分】🌸
银光跃动！被锦鲤尾巴甩到啦！
(=´ω｀=)ノ樱花雨中飘来半个小月亮🌙
再摸一次说不定能凑成整圆哦～"""
small = """🎉【20积分】🎉
叮咚！摸到会跳舞的胖海星✨
( ˘͈ ᵕ ˘͈ )小精灵给你撒彩虹糖啦！
恭喜小可爱触发暴击按钮ฅ^•ﻌ•^ฅ"""
normal = [
    "噗叽！小仓鼠打喷嚏喷出{{prize}}积分ฅ(≈●ܫ●≈)ฅ",
    "奶茶珍珠弹弹弹～接住{{prize}}颗积分波波(๑´ㅂ`๑)♡",
    "魔法荷包蛋煎出{{prize}}积分！要加番茄酱吗～( ๑❛ᴗ❛๑)",
    "柴犬滑板路过，掉出{{prize}}积分骨头🛹ฅ•ω•ฅ汪！",
    "棉花云朵里抖出{{prize}}积分毛毛～要凑成小枕头吗(ˊᵒ̴̶̷̤ ꇴ ᵒ̴̶̷̤ˋ)",
    "兔兔存钱罐吐出{{prize}}枚胡萝卜币🥕(=ↀωↀ=)✧",
    "喵爪按钮拍出{{prize}}朵小鱼干烟花🎇ฅ^•ﻌ•^ฅ",
    "星星糖罐摇出{{prize}}粒甜积分✨( *´﹀`* )♬°"
]
empty = """🐟【0积分】🐟
咕噜噜…摸到空气泡啦 (´•̥ ̯ •̥`)
小章鱼悄悄叼走了你的积分币~
摸摸头，鱼塘主给你留了安慰小鱼干ฅ'ω'ฅ✨"""
probabilities = """
🎣【摸鱼概率】🎣
🌟99积分：0.299%
🌸50积分：0.598%
🎉20积分：2.215%
🐟0积分：4.983%
🥕其他积分：91.905%
"""
